### PR TITLE
Modified JSON transform

### PR DESCRIPTION
**Pull request by michaeldavie**
I added [0] to the JSON path, which prevents the [] characters from being returned and allows for simpler handling.

### CODE REVIEW

**Comment by michaeldavie** [comment]
While this change works in openHAB v1.8.3, I've confirmed that a different syntax is required in v2.0b4. See https://community.openhab.org/t/jsonpath-transform-in-oh2-http-binding/4715 for more background.

**Comment by sheppy99** [comment]
That's interesting, presumably the original, which I found largely by trial and error, doesn't work on OH2?
I've been putting off the OH2 journey so far as everything is working well on OH 1.8, and I have a lot of things automated!
I'll give your mod a test later this week and merge it in. I'm always up for simplifying things, assuming it doesn't open up the door for unexpected consequences further down the track
Cheers
Kevin

Sent from my iPhone

On 21/11/2016, at 6:01 PM, michaeldavie <notifications@github.com<mailto:notifications@github.com>> wrote:

While this change works in openHAB v1.8.3, I've confirmed that a different syntax is required in v2.0b4. See https://community.openhab.org/t/jsonpath-transform-in-oh2-http-binding/4715 for more background.

##

**Review by sheppy99 — APPROVED** [review]
Looks good and simplifies things too - thanks very much!
Please let me know if you get working Openhab 2 code and I'll either add it here or put a link into your copy if you prefer

**Comment by michaeldavie** [comment]
Awesome. I got it working in openHAB 2.0b4 as well, though I'll admit that I'm not sure why it works, as the results are not what I'd expect. Regardless, here's the code:
```
var String Heatpump1On = (transform("JSONPATH", "$.result..on[0]", Heatpump1Status))
val Number Heatpump1TemperatureValue = new Double(transform("JSONPATH", "$.result[0].temperature", Heatpump1Measurements))
val Number Heatpump1HumidityValue = new Double(transform("JSONPATH", "$.result[0].humidity", Heatpump1Measurements))
val Number Heatpump1Battery = new Double(transform("JSONPATH", "$.result[0].batteryVoltage", Heatpump1Measurements))

**Comment by sheppy99** [comment]
Well done. OH2 is something I'll move to eventually. My current system controls so much that I'm in no hurry to discover the inevitable growing pains. It's also heading into summer and I have a roof to replace. Are you in the lesser crowded hemisphere per chance?

Sent from my iPhone

On 22/11/2016, at 4:23 PM, michaeldavie <notifications@github.com<mailto:notifications@github.com>> wrote:

Awesome. I got it working in openHAB 2.0b4 as well, though I'll admit that I'm not sure why it works, as the results are not what I'd expect. Regardless, here's the code:

var String Heatpump1On = (transform("JSONPATH", "$.result..on[0]", Heatpump1Status))
val Number Heatpump1TemperatureValue = new Double(transform("JSONPATH", "$.result[0].temperature", Heatpump1Measurements))
val Number Heatpump1HumidityValue = new Double(transform("JSONPATH", "$.result[0].humidity", Heatpump1Measurements))
val Number Heatpump1Battery = new Double(transform("JSONPATH", "$.result[0].batteryVoltage", Heatpump1Measurements))

##

**Comment by michaeldavie** [comment]
No, I'm in Canada. We're heading into winter here, so it's actually the perfect time for me to tinker. My main use case is getting my Nest to control my Sensibo for AC in the summer. I've been using a Ruby kludge that I wrote myself for this so far, and I just stumbled onto openHAB a couple weeks ago. It's waaay slicker, and I've got a few months to get my functionality moved over. I'm toying with the idea of writing a Sensibo binding for openHAB 2 as well; we'll see where that goes.

**Comment by sheppy99** [comment]
Heading into Winter is a good time to tinker. We’re heading into Summer and the bedroom faces West so it gets way too hot to sleep in. I have a set of rules that samples the bedroom temperature every 5 minutes and turns the cooling on if it gets too hot. It knows the time we are heading to bed and it knows my guestimate of how many minutes it takes to cool a degree.
It was something I expected Sensibo to do when I bought it, but when it didn’t I decided to write my own.
If you are learning Openhab from scratch I’d suggest going straight to V2, from what I know its similar but not the same

**Comment by sheppy99** [comment]
I’ve created a new repository with the V2 code in it, https://github.com/sheppy99/Sensibo-and-Openhab-2/blob/master/README.md
any chance you can take a look? Also would you like me to credit you with the changes?
Thanks for your help
Cheers

**Comment by michaeldavie** [comment]
Thanks, I will. I've only implemented the read function so far, but I'll let you know if I come across any other changes.

**Pull request closed without merging**
